### ISSUE TITLE
New Protocol: Connections to trusted relayers and sequencer IDs

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-local-collector#11]
**Is your feature request related to a problem?**
The local collector should establish connection to relayers and/or sequencers by fetching their identity from a trusted source: an open Github repository in this case where realyer and sequencer identities are added in a trustful, verifiable manner.

**Describe the solution you'd like**
By fetching such identites from a trusted, bootstrap repo like the above, the collector should proceed to form connection in the following order of priority.

1. Attempt to connect to libp2p circuit relayers that accept snapshot submissions and forward it to the sequencer, thereby getting around blocks and censorship attempts.
2. Only upon the failure of the above strategy, attempt to directly initiate connections with the sequencer.
3. Supply a configuration flag to switch between the above two strategies.

**Describe alternatives you've considered**
Any open, federated protocol like Rendezvous is open to abuse and masquerade from malicious parties. Also increases the latency and complexity of routing via relayers to sequencers.

**Additional context**
NA

**Comment by Sulejman** [comment]
Tested by me and contains tests:

https://github.com/PowerLoom/snapshotter-lite-local-collector/tree/feat/trusted-relayers

Pending internal test and review, merge and integration with main branch.

**Comment by Sulejman** [comment]
After sync with @anomit :

- [ ] Relayers: 
- [ ] Implement proper env handling in collector
- [ ] Open system resources for submission relayer
- [ ] Test with open relay resources
- [ ] Implement fallback string for list url (relayers list)
